### ISSUE TITLE
本地测试出现！

### ISSUE THREAD

**Issue by xiamuguizhi** [hqweay/php-blog#1]
Warning: mysqli_fetch_array() expects parameter 1 to be mysqli_result, boolean given in F:\phpStudy\WWW\index.php on line 39

**Comment by hqweay** [comment]
如果已经按步骤创好了数据库的话，那一定是因为我写的太不严谨了（非常抱歉），你可以尝试创建文章后再刷新首页试一下。

**Comment by xiamuguizhi** [comment]
@hqweay 发现原因了 我切换到php5.6正常了  原本的是php5.3
